import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Shahid M - Home",
  description: "Generated by create next app",
};
export default function page() {
  return (
    <div className="text-red-400 px-[18.3%] pt-3 w-full flex items-center justify-center h-screen">
      This page is under development
    </div>
  );
}
