import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Shahid M - Home",
  description: "Generated by create next app",
};
export default function page() {
  return <div className="text-red-400">About</div>;
}
