import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import { AppProvider } from "@/context/ContextApi";
import SmoothScroll from "@/context/SmoothScroll";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Dev Imran - Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
(function () {
  const theme = localStorage.getItem("theme")
  if (theme === "dark") {
    document.documentElement.classList.add("dark")
  } else {
    document.documentElement.classList.remove("dark")
  }
})();
`,
          }}
        />
      </head>
      <body className={`${poppins.className} max-w-[1920px] mx-auto `}>
        <SmoothScroll />
        <div id="smooth-wrapper">
          <div id="smooth-content">
            <AppProvider>
              <Navbar />
              {children}
            </AppProvider>
          </div>
        </div>
      </body>
    </html>
  );
}
