import type { Metadata } from "next";
import { DM_Sans, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import { AppProvider } from "@/context/ContextApi";
import { Toaster } from "sonner";
import Footer from "@/components/Footer/Footer";

const dm_sans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Dev Imran - Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
(function () {
  const theme = localStorage.getItem("theme")
  if (theme === "dark") {
    document.documentElement.classList.add("dark")
  } else {
    document.documentElement.classList.remove("dark")
  }
})();
`,
          }}
        />
      </head>
      <body className={`${dm_sans.className} max-w-[1920px] mx-auto `}>
        <AppProvider>
          <Navbar />
          {children}
          <Footer />
          <Toaster />
        </AppProvider>
      </body>
    </html>
  );
}
